import { defineConfig, presetUno } from "unocss";
import { presetIcons } from "@unocss/preset-icons";

export default defineConfig({
  presets: [presetUno(), presetIcons({ scale: 1 })],
  shortcuts: {
    // Explicit transition properties (replaces `transition-all`) so only the
    // intended, compositor-friendly properties animate.
    "transition-interactive":
      "transition-[color,background-color,border-color,transform,box-shadow,opacity]",
  },
  safelist: [
    "bg-gradient-to-br",
    "i-lucide-alert-circle",
    "i-lucide-alert-triangle",
    "i-lucide-arrow-right",
    "i-lucide-check",
    "i-lucide-check-circle",
    "i-lucide-chevron-down",
    "i-lucide-chevron-left",
    "i-lucide-chevron-right",
    "i-lucide-chevron-up",
    "i-lucide-copy",
    "i-lucide-dices",
    "i-lucide-eye",
    "i-lucide-eye-off",
    "i-lucide-folder-open",
    "i-lucide-grip-vertical",
    "i-lucide-image",
    "i-lucide-image-off",
    "i-lucide-image-plus",
    "i-lucide-info",
    "i-lucide-keyboard",
    "i-lucide-layers",
    "i-lucide-lock",
    "i-lucide-monitor",
    "i-lucide-maximize-2",
    "i-lucide-palette",
    "i-lucide-plus",
    "i-lucide-power",
    "i-lucide-power-off",
    "i-lucide-redo-2",
    "i-lucide-repeat",
    "i-lucide-rotate-ccw",
    "i-lucide-save",
    "i-lucide-search",
    "i-lucide-shield",
    "i-lucide-trash-2",
    "i-lucide-triangle-alert",
    "i-lucide-undo-2",
    "i-lucide-unlock",
    "i-lucide-x",
    "i-lucide-zap",
    "i-lucide-zoom-in",
    "i-lucide-zoom-out",
    "from-orange-950/60",
    "from-orange-950/50",
    "from-orange-950/40",
    "from-red-950/40",
    "from-neutral-800/50",
    "from-neutral-900/60",
    "from-neutral-900/50",
    "from-green-950/40",
    "from-cyan-950/40",
    "from-purple-950/40",
    "from-blue-950/40",
    "from-pink-950/40",
    "to-neutral-950/60",
    "to-yellow-950/30",
    "to-yellow-950/20",
    "to-purple-950/40",
    "to-amber-950/30",
    "to-blue-950/40",
    "to-red-950/30",
    "to-neutral-800/60",
    "to-cyan-950/40",
    "to-teal-950/40",
    "to-orange-950/30",
    "to-green-950/30",
    "from-emerald-950/60",
    "to-black/60",
  ],
  theme: {
    fontFamily: {
      display: ['"Instrument Serif"', "ui-serif", "Georgia", "serif"],
      mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
    },
    colors: {
      orange: {
        400: "#d47534",
        500: "#b85c2a",
        600: "#96461d",
        950: "#221005",
      },
    },
  },
});
